package com.example.demo.Enums;

public enum FilterType {
   AGE, AGE_RANGE, ALIVE, DEAD, BIRTHDATE, BIRTHDATE_RANGE, DEATHDATE, DEATHDATE_RANGE, COW, HEIFER, STEER, BULL, FEMALE, MALE, WEIGHT_RANGE
}
